<?php

/**
 * BaseCustomerCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Customers
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getCustomers() Returns the current record's "Customers" collection
 * @method CustomerCategory    setName()      Sets the current record's "name" value
 * @method CustomerCategory    setCustomers() Sets the current record's "Customers" collection
 * 
 * @package    board
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomerCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Customer as Customers', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}