<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/25 13:01:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=c1board',
  'username' => 'root',
  'password' => 'pV5pf8B4',
  'name' => 'doctrine',
)),);
