<?php

/**
 * CustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CustomerTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Customer');
    }

    public function getActiveCustomers() {
        $q = $this->createQuery('q')
                ->where('is_activated = ? ', true)
                ->orderBy('updated_at ASC');

        return $q->execute();
    }

}